### PR TITLE
Include subreddit_reader and with_webserver example.

### PR DESCRIPTION
**Pull request by steadylearner**
I included two examples.

**1. Bot to show Rust latest posts from Rust subreddit.**
**2. How to use Teloxide with another Rust webframework.**

The only problem was that I couldn't find how to fix the problem with MarkdownV2 and also tested with HTML for this example but had the problem below.

```rust
let for_markdown = remove_double_quote(f!("{num}. {post_link}\n"));
```

with

```rust
ERROR teloxide::error_handlers > Error: ApiError { status_code: 400, kind: Other }
```

Then, [I simplified the example and it worked without errors.](https://github.com/steadylearner/Rust-Full-Stack/blob/master/bots/teloxide/src/html/main.rs)

I think some parts in the subreddit_reader example other than code from your crate may be affecting the output. So it is hard for me to find where the problem is.

But, I think the example itself can be helpful to many people except it shows deprecated warning for Markdown. I hope you can help me to correct that if you think it is necessary.  I thought that **MarkdownV2** should work also when the **Markdown** work.

Thanks for your help. I am planning to experiment more your crate and would write a blog post for this.

### CODE REVIEW

**Comment by Hirrolot** [comment]
Thank you for a good bot!

> I thought that MarkdownV2 should work also when the Markdown work.

Not necessarily, because MarkdownV2 is not backwards compatible with Markdown.

**Comment by steadylearner** [comment]
Ok. Thanks for the review.

 I hope this can be a starting point for others to commit to your repository more.

**Comment by Hirrolot** [comment]
So after experimenting with parse modes, I suggest you just use `ParseMode::HTML` because it doesn't cause problems that cause `ParseMode::{Markdown, MarkdownV2}`. For example, telegram clients don't want to parse this markdown text (and I don't know why):

```
[\[example\]](https://www.example.com)
```

Some people [say](https://stackoverflow.com/questions/40626896/telegram-does-not-escape-some-markdown-characters) to not escape the `]` character, but the following text:

```
[\[example]](https://www.example.com)
```

Doesn't work too!

**Comment by steadylearner** [comment]
Thanks for searching the information. I edited the example to use HTML instead.

**Pull request merged**
